// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv cloudflare-env.d.ts`

interface CloudflareEnv {
	NEXT_CACHE_WORKERS_KV: KVNamespace;
	NEXTJS_ENV: string;
	ASSETS: Fetcher;
	// Add custom environment variables
	DISCORD_TOKEN?: string;
	DISCORD_GUILD_ID?: string;
}
