main = ".open-next/worker.js"
name = "news-fasttakeoff-org"
compatibility_date = "2025-03-11"
compatibility_flags = ["nodejs_compat"]

[triggers]
crons = ["0 * * * *", "2 * * * *"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[kv_namespaces]]
binding = "EXECUTIVE_ORDERS_CACHE"
id = "af457f4cbb8d43659858f3fdc7b9b697"
preview_id = "2238ece0feef4906ac64958dd0f5a726"

[[kv_namespaces]]
binding = "REPORTS_CACHE"
id = "1907c22aa1e24a0e98f995ffcbb7b9aa"
preview_id = "28b5902427594e4287a4109863c7bd19"

[[kv_namespaces]]
binding = "CHANNELS_CACHE"
id = "8cf4b17a28e043059145354652cb7149"
preview_id = "69085ad48ebb44d5a4131b3e3089efb4"

[[kv_namespaces]]
binding = "MESSAGES_CACHE"
id = "b3ca706f58e44201a1f3d362c358cd1c"
preview_id = "a51ee099a3cb42eca2e143005e0b2558"

[[kv_namespaces]]
binding = "SUBSCRIPTIONS_CACHE"
id = "f16280a6d9a14d228556662cf469926c"
preview_id = "81c54163e8c443c88cf644d6db59b766"

[[kv_namespaces]]
binding = "AUTH_TOKENS"
id = "9ce83d624a074ec9bec17d43d8b3af08"
preview_id = "4630becfa25c48db8d81ee761e58427d"

[[kv_namespaces]]
binding = "GEOCODE_CACHE"
id = "626d83761ccf42f099a1d0211f61abc8"
preview_id = "9d2d1f80fd3847f89e000a392922bee0"

[[kv_namespaces]]
binding = "FEEDS_CACHE"
id = "570aca506a0c42a3bbae031791885844"
preview_id = "4bc7359368524a13a666e1bfbb177802"

# R2 bucket binding for Instagram images
[[r2_buckets]]
binding = "INSTAGRAM_IMAGES"
bucket_name = "news-images"
preview_bucket_name = "news-images-dev"

[[d1_databases]]
binding = "DB"
database_name = "prod-emails"
database_id = "06082f10-b7ba-4a98-bf03-5c4ac36a6e36"

[[routes]]
pattern = "news.fasttakeoff.org"
custom_domain = true
zone_name = "fasttakeoff.org"

[vars]
NEXT_PUBLIC_CLERK_SIGN_IN_URL = "/sign-in"
NEXT_PUBLIC_CLERK_SIGN_UP_URL = "/sign-up"
NEXT_PUBLIC_CLERK_SIGN_IN_FORCE_REDIRECT_URL = "/"
NEXT_PUBLIC_CLERK_SIGN_UP_FORCE_REDIRECT_URL = "/"
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY = "pk_live_Y2xlcmsuZmFzdHRha2VvZmYub3JnJA"
NEXT_PUBLIC_API_URL = "https://news.fasttakeoff.org"
SERVER_API_URL = "https://news.fasttakeoff.org"
R2_PUBLIC_URL = "https://images.fasttakeoff.org"
FACEBOOK_APP_ID = "1279507170438935"
FACEBOOK_PAGE_ID = "818480904670711"

[placement]
mode = "smart"

[observability.logs]
enabled = true