main = ".open-next/worker.js"
name = "news-aiworld-com-br"
compatibility_date = "2025-03-11"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[kv_namespaces]]
binding = "NEXT_CACHE_WORKERS_KV"
id = "2b5d6df3cfc54116b6e34000be4b71a3"
preview_id = "2b5d6df3cfc54116b6e34000be4b71a3"

[[kv_namespaces]]
binding = "REPORTS_CACHE"
id = "1907c22aa1e24a0e98f995ffcbb7b9aa"
preview_id = "1907c22aa1e24a0e98f995ffcbb7b9aa"

[[kv_namespaces]]
binding = "CHANNELS_CACHE"
id = "8cf4b17a28e043059145354652cb7149"

[[routes]]
pattern = "news.aiworld.com.br"
custom_domain = true
zone_name = "aiworld.com.br"

[vars]
DISCORD_TOKEN = "NzUwMzQyOTExODkxMDc5MTY5.GlHsx6.3cuRXm1lFqvyyOjxk_woZD197i59kbNv5HNP-E"
DISCORD_GUILD_ID = "1108138416660557926"
GROQ_API_KEY = "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"

[observability.logs]
enabled = true