main = ".open-next/worker.js"
name = "news-fasttakeoff-org"
compatibility_date = "2025-03-11"
compatibility_flags = [
    "nodejs_compat",
]

[triggers]
# Every 2 hours (0:00, 2:00, 4:00, etc) for 2h reports
# Every 6 hours (0:00, 6:00, 12:00, 18:00) for 6h reports and executive summary
# Every 15 minutes for message updates
# Every 1 hour for MktNews summary and cache maintenance
crons = [
    "0 */2 * * *",    # 2h reports and feeds summaries
    "0 */6 * * *",    # 6h reports and executive summary
    "*/15 * * * *",   # Message updates
    "0 * * * *"       # MktNews summary and cache maintenance (hourly)
]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[kv_namespaces]]
binding = "EXECUTIVE_ORDERS_CACHE"
id = "af457f4cbb8d43659858f3fdc7b9b697"
preview_id = "2238ece0feef4906ac64958dd0f5a726"

[[kv_namespaces]]
binding = "REPORTS_CACHE"
id = "1907c22aa1e24a0e98f995ffcbb7b9aa"
preview_id = "28b5902427594e4287a4109863c7bd19"

[[kv_namespaces]]
binding = "CHANNELS_CACHE"
id = "8cf4b17a28e043059145354652cb7149"
preview_id = "69085ad48ebb44d5a4131b3e3089efb4"

[[kv_namespaces]]
binding = "MESSAGES_CACHE"
id = "b3ca706f58e44201a1f3d362c358cd1c"
preview_id = "a51ee099a3cb42eca2e143005e0b2558"

[[kv_namespaces]]
binding = "SUBSCRIPTIONS_CACHE"
id = "f16280a6d9a14d228556662cf469926c"
preview_id = "81c54163e8c443c88cf644d6db59b766"

[[kv_namespaces]]
binding = "AUTH_TOKENS"
id = "9ce83d624a074ec9bec17d43d8b3af08"
preview_id = "4630becfa25c48db8d81ee761e58427d"

[[kv_namespaces]]
binding = "GEOCODE_CACHE"
id = "626d83761ccf42f099a1d0211f61abc8"
preview_id = "9d2d1f80fd3847f89e000a392922bee0"

[[kv_namespaces]]
binding = "FEEDS_CACHE"
id = "570aca506a0c42a3bbae031791885844"
preview_id = "4bc7359368524a13a666e1bfbb177802"

[[kv_namespaces]]
binding = "ENTITIES_CACHE"
id = "60c184aac065460db20c1a6d07355cba"
preview_id = "206f66b9c1b44d5d8b2904bf22b3b006"

[[kv_namespaces]]
binding = "SITEMAP_CACHE"
id = "3833f947b0244c2f9a8aebf2d2fa528f"
preview_id = "7e534ee4e7b14c588e474b8570e0b48a"

[[kv_namespaces]]
binding = "EXECUTIVE_SUMMARIES_CACHE"
id = "3631df94eaa7437882b4c9e739d8d4e5"
preview_id = "32a010bc0d60478fb5fc37a268e67d10"

[[kv_namespaces]]
binding = "MKTNEWS_CACHE"
id = "ee7573e6ee69407c8821fbef216929fa"
preview_id = "bad88df0ebe6481baeac45dbc325b523"

[[kv_namespaces]]
binding = "MKTNEWS_SUMMARIES_CACHE"
id = "93a1fbc86d214a2fa1226f8266d99775"
preview_id = "68a0fc75352242dcb7b8344c855d6cda"

# R2 bucket binding for Instagram images
[[r2_buckets]]
binding = "INSTAGRAM_IMAGES"
bucket_name = "news-images"
preview_bucket_name = "news-images-dev"

[[d1_databases]]
binding = "DB"
database_name = "prod-emails"
database_id = "06082f10-b7ba-4a98-bf03-5c4ac36a6e36"

[[routes]]
pattern = "news.fasttakeoff.org"
custom_domain = true
zone_name = "fasttakeoff.org"

[vars]
NEXT_PUBLIC_CLERK_SIGN_IN_URL = "/sign-in"
NEXT_PUBLIC_CLERK_SIGN_UP_URL = "/sign-up"
NEXT_PUBLIC_CLERK_SIGN_IN_FORCE_REDIRECT_URL = "/"
NEXT_PUBLIC_CLERK_SIGN_UP_FORCE_REDIRECT_URL = "/"
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY = "pk_live_Y2xlcmsuZmFzdHRha2VvZmYub3JnJA"
NEXT_PUBLIC_API_URL = "https://news.fasttakeoff.org"
SERVER_API_URL = "https://news.fasttakeoff.org"
R2_PUBLIC_URL = "https://images.fasttakeoff.org"
FACEBOOK_APP_ID = "1279507170438935"
FACEBOOK_PAGE_ID = "818480904670711"
DISCORD_DISABLED = "0"

[placement]
mode = "smart"

[observability.logs]
enabled = true