main = ".open-next/worker.js"
name = "news-aiworld-com-br"
compatibility_date = "2025-03-11"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[kv_namespaces]]
binding = "NEXT_CACHE_WORKERS_KV"
id = "2b5d6df3cfc54116b6e34000be4b71a3"

[[routes]]
pattern = "news.aiworld.com.br"
custom_domain = true
zone_name = "aiworld.com.br"

[vars]
DISCORD_GUILD_ID = "1108138416660557926"