import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Privacy Policy - Fast Takeoff News',
    description: 'Privacy Policy for Fast Takeoff News-IG app.',
};

export default function PrivacyPolicy() {
    return (
        <div className="container mx-auto px-4 py-8">
            <h1 className="text-3xl font-bold mb-4">Privacy Policy for Fast Takeoff News-IG</h1>
            <p className="text-sm text-gray-600 mb-4">Last updated: April 28, 2025</p>

            <section className="mb-6">
                <h2 className="text-xl font-semibold mb-2">Introduction</h2>
                <p>
                    Fast Takeoff News-IG (&quot;we&quot;, &quot;us&quot;, or &quot;our&quot;) is an application that generates and posts news content to Instagram on behalf of users. This Privacy Policy explains how we collect, use, and protect your data when you use our app through Meta&apos;s Instagram Graph API.
                </p>
            </section>

            <section className="mb-6">
                <h2 className="text-xl font-semibold mb-2">Data We Collect</h2>
                <p>We collect the following data to provide our services:</p>
                <ul className="list-disc pl-5">
                    <li><strong>Instagram Account Data:</strong> We access your Instagram Business or Creator account details, including your user ID and media posting permissions, via the Instagram Graph API.</li>
                    <li><strong>Generated News Content:</strong> News pieces generated by our app, including titles, content, and optional images, which are posted to your Instagram account.</li>
                </ul>
            </section>

            <section className="mb-6">
                <h2 className="text-xl font-semibold mb-2">How We Use Your Data</h2>
                <p>Your data is used solely for the following purpose:</p>
                <ul className="list-disc pl-5">
                    <li>To authenticate with the Instagram Graph API and post news content to your Instagram account.</li>
                </ul>
            </section>

            <section className="mb-6">
                <h2 className="text-xl font-semibold mb-2">Data Storage and Security</h2>
                <p>
                    We store your Instagram access tokens securely using Cloudflare Workers Secrets. Generated news content is temporarily stored during the posting process and not retained after posting. We implement reasonable security measures to protect your data from unauthorized access.
                </p>
            </section>

            <section className="mb-6">
                <h2 className="text-xl font-semibold mb-2">Data Sharing</h2>
                <p>
                    We do not share your data with third parties, except as required to interact with the Instagram Graph API to post content on your behalf.
                </p>
            </section>

            <section className="mb-6">
                <h2 className="text-xl font-semibold mb-2">Your Rights</h2>
                <p>
                    You can revoke our app&apos;s access to your Instagram account at any time through your Instagram settings. If you have questions about your data or wish to request its deletion, please contact us at gsaboia@yahoo.com.
                </p>
            </section>

            <section className="mb-6">
                <h2 className="text-xl font-semibold mb-2">Contact Us</h2>
                <p>
                    For any questions or concerns about this Privacy Policy, please contact us at gsaboia@yahoo.com.
                </p>
            </section>
        </div>
    );
}