name: Deploy News App

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Clean install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_DEPLOY_KEY }}
      - name: Deploy to server
        run: |
          /usr/bin/rsync -av --delete \
            -e "ssh -o StrictHostKeyChecking=no" \
            --exclude='.git*' --exclude='node_modules' \
            --exclude='src' --exclude='*.md' \
            ./out/ \
            deployer@138.68.163.17:/var/www/aiworld-sites/news.aiworld.com.br/html/
